"""Extra unlinked OPTCG landing pages: sets, compares, how-tos, searches, names."""

# Leader indices match generate-seo-pages.LEADERS
# 0 Newgate 1 Shanks 2 Rocks 3 Kaido 4 OP17 Luffy 5 Linlin 6 RG
# 7 Nami 8 Mihawk 9 OP16 Ace 10 OP13 Ace 11 Imu 12 Enel 13 Katakuri
# 14 Rosinante 15 Sabo 16 Moria 17 Robin

EXTRA_TOPICS = [
    {
        "slug": "one-piece-card-game-english",
        "title": "One Piece Card Game English | OPTCG",
        "h2": "English OPTCG",
        "desc": "English One Piece Card Game (OPTCG) decklists for Bandai constructed play.",
        "copy": "English OPTCG uses the Bandai ONE PIECE CARD GAME card text hosted on this fan site via Limitless. Open a leader page for 50-card lists with English names.",
        "leaders": [2, 3, 4, 8, 15],
    },
    {
        "slug": "optcg-english",
        "title": "OPTCG English decklists | One Piece TCG",
        "h2": "OPTCG English",
        "desc": "English OPTCG decklists and leader pages for the Bandai card game.",
        "copy": "If you searched OPTCG English, these are constructed 50-card lists with English card names. Start with OP17 Rocks, Kaido, or Black Luffy, then current-format pages like Mihawk and Sabo.",
        "leaders": [2, 3, 4, 8, 15],
    },
    {
        "slug": "op-17",
        "title": "OP-17 One Piece TCG | World's Strongest Warriors",
        "h2": "OP-17",
        "desc": "OP-17 is OP17 The World's Strongest Warriors. Browse OPTCG leader lists.",
        "copy": "OP-17 and OP17 are the same English booster, The World's Strongest Warriors. The six OP17 leaders on this site are Rocks D. Xebec, Kaido, Monkey D. Luffy, Charlotte Linlin, Shanks, and Edward Newgate.",
        "leaders": [2, 3, 4, 5, 1, 0],
    },
    {
        "slug": "the-worlds-strongest-warriors",
        "title": "The World's Strongest Warriors | OP17 OPTCG",
        "h2": "The World's Strongest Warriors",
        "desc": "OP17 The World's Strongest Warriors leaders and 50-card OPTCG lists.",
        "copy": "The World's Strongest Warriors is the English name for OP17. Use the six OP17 leader pages for tournament and community 50-card lists.",
        "leaders": [2, 3, 4, 5, 1, 0],
    },
    {
        "slug": "optcg-meta-2026",
        "title": "OPTCG meta 2026 | OP17 One Piece TCG",
        "h2": "OPTCG meta 2026",
        "desc": "2026 OPTCG meta leaders with Limitless tournament lists on this fan site.",
        "copy": "Early 2026 constructed play on Limitless is heavy on OP17 Rocks and Kaido, plus Mihawk, Sabo, and RG Luffy. Lists here are copied from those events, newest date first — not invented rankings.",
        "leaders": [2, 3, 8, 15, 6, 4],
    },
    {
        "slug": "best-optcg-decks",
        "title": "Best OPTCG decks | One Piece TCG lists",
        "h2": "Best OPTCG decks",
        "desc": "Recent OPTCG decks with Limitless lists: Rocks, Kaido, Mihawk, Sabo, and more.",
        "copy": "There is no official best deck. This page points at the leaders posting the most recent Limitless lists: Rocks D. Xebec, Kaido, Mihawk, Sabo, RG Luffy, and OP17 Black Luffy. Open a page and copy a 50-card list.",
        "leaders": [2, 3, 8, 15, 6, 4],
    },
    {
        "slug": "optcg-tournament-deck",
        "title": "OPTCG tournament deck | Limitless lists",
        "h2": "OPTCG tournament deck",
        "desc": "Tournament OPTCG decks copied from Limitless Play standings.",
        "copy": "Tournament rows on each leader page are 50-card lists from public Limitless Play events. They are sorted by event date, newest first. Community YouTube lists sit in a separate block when they exist.",
        "leaders": [2, 3, 8, 15],
    },
    {
        "slug": "one-piece-tcg-tournament",
        "title": "One Piece TCG tournament lists | OPTCG",
        "h2": "One Piece TCG tournament",
        "desc": "One Piece TCG tournament decklists from Limitless constructed events.",
        "copy": "Bandai store play, Treasure Cups, and online cups all use 50 cards plus a leader. This fan site copies public Limitless standings onto leader pages so you can study a list before you register.",
        "leaders": [2, 8, 3, 15],
    },
    {
        "slug": "store-championship",
        "title": "OPTCG store championship | One Piece TCG",
        "h2": "Store championship",
        "desc": "Store championship OPTCG is constructed 50-card. Browse leader lists here.",
        "copy": "Store championships use official Bandai constructed rules. Study a list on this site, then check Bandai’s events page for a shop championship near you. We do not post pairings or fake results.",
        "leaders": [2, 3, 8, 6],
    },
    {
        "slug": "optcg-beginner",
        "title": "OPTCG beginner decklists | One Piece TCG",
        "h2": "OPTCG beginner",
        "desc": "Beginner OPTCG starting point: pick a leader, open a 50-card list.",
        "copy": "New to OPTCG? A constructed deck is 50 cards plus a leader. Open a popular leader — Mihawk, Rocks, or RG Luffy — and copy the consensus list. Hover a name for the English card picture.",
        "leaders": [8, 2, 6, 7],
    },
    {
        "slug": "how-to-build-optcg-deck",
        "title": "How to build an OPTCG deck | 50-card",
        "h2": "How to build an OPTCG deck",
        "desc": "How to build a 50-card One Piece TCG deck: leader, characters, events, stages.",
        "copy": "Pick a leader color, then fill 50 cards. Most lists here run 4-ofs of the engine cards, a few events, and sometimes a stage. Copy a consensus list from a leader page instead of guessing ratios.",
        "leaders": [2, 8, 6, 15],
    },
    {
        "slug": "optcg-50-card",
        "title": "OPTCG 50-card deck | One Piece TCG",
        "h2": "50-card OPTCG",
        "desc": "Constructed OPTCG is 50 cards plus a leader. Browse full lists here.",
        "copy": "Every tournament row on this site is a full 50-card OPTCG list: characters, events, and stages, plus the leader. The consensus block averages those lists and fills back to 50.",
        "leaders": [2, 3, 8, 15],
    },
    {
        "slug": "optcg-don",
        "title": "DON!! OPTCG | One Piece TCG DON cards",
        "h2": "DON!!",
        "desc": "DON!! powers OPTCG attacks. See constructed lists that spend DON!!.",
        "copy": "DON!! is the resource in the One Piece Card Game. Leader effects often say DON!! −1 or DON!! x1. Open Kaido, Enel, Katakuri, or Rosinante for lists that spend DON!! as part of the game plan.",
        "leaders": [3, 12, 13, 14],
    },
    {
        "slug": "optcg-life",
        "title": "Life cards OPTCG | One Piece TCG",
        "h2": "Life cards",
        "desc": "OPTCG life totals and life-gain leaders such as Gecko Moria and Rosinante.",
        "copy": "Leaders list a life total on the card. Some effects add life (Gecko Moria) or spend life to save a body (Donquixote Rosinante). Yellow Linlin also plays around life. Open those pages for 50-card lists.",
        "leaders": [16, 14, 5, 15],
    },
    {
        "slug": "optcg-trigger",
        "title": "Trigger OPTCG | One Piece TCG",
        "h2": "Trigger",
        "desc": "Trigger cards in OPTCG, including Nico Robin lists that trash a Trigger.",
        "copy": "Trigger is a card keyword in the One Piece TCG. Nico Robin trashes a Trigger to rest a DON!!. Yellow and dual-color lists often keep Trigger events. Open Robin, Linlin, and Nami for examples.",
        "leaders": [17, 5, 7, 16],
    },
    {
        "slug": "optcg-banish",
        "title": "Banish OPTCG | Nico Robin One Piece TCG",
        "h2": "Banish",
        "desc": "Banish in OPTCG trashes damage without a Trigger. See Nico Robin lists.",
        "copy": "Banish means damage is trashed without activating Trigger. OP09 Nico Robin is the banish leader on this site. Open her page for 50-card lists, including recent copies with OP17 cards.",
        "leaders": [17],
    },
    {
        "slug": "optcg-rush",
        "title": "Rush OPTCG | One Piece TCG",
        "h2": "Rush",
        "desc": "Rush OPTCG lists, including red OP16 Portgas D. Ace.",
        "copy": "Rush lets a character attack the turn it is played. Red OP16 Ace gives Rush to a Luffy or an 8000-power Whitebeard Pirate. That is not red/blue OP13 Ace. Open the OP16 Ace page for rush lists.",
        "leaders": [9, 0, 6],
    },
    {
        "slug": "optcg-blocker",
        "title": "Blocker OPTCG | One Piece TCG",
        "h2": "Blocker",
        "desc": "Blocker OPTCG decks: Black Luffy, Imu, and other midrange lists.",
        "copy": "Blocker characters take attacks for you. Black OP17 Luffy / Elbaph and black Imu lists play a lot of them. Open those leader pages for constructed blocker packages.",
        "leaders": [4, 11, 8],
    },
    {
        "slug": "dual-color-optcg",
        "title": "Dual color OPTCG | One Piece TCG",
        "h2": "Dual color",
        "desc": "Dual-color OPTCG leaders: RG Luffy, Nami, Ace, Sabo, Rosinante, Robin, Moria.",
        "copy": "Dual-color leaders play two colors in one 50-card list. On this site that is RG Luffy, Nami, OP13 Ace, Sabo, Donquixote Rosinante, Nico Robin, and Gecko Moria.",
        "leaders": [6, 7, 10, 15, 14, 17, 16],
    },
    {
        "slug": "optcg-colors",
        "title": "OPTCG colors | One Piece TCG",
        "h2": "OPTCG colors",
        "desc": "Red, green, blue, purple, black, and yellow OPTCG leader pages.",
        "copy": "OPTCG has six colors. OP17 prints one leader per color. Dual-color leaders mix two. Use the color guide pages or open a leader that matches the cards you pulled.",
        "leaders": [0, 1, 2, 3, 4, 5],
    },
    {
        "slug": "god-valley",
        "title": "God Valley One Piece TCG | OPTCG",
        "h2": "God Valley",
        "desc": "God Valley OPTCG lists live on OP17 Rocks D. Xebec.",
        "copy": "God Valley names in the card game sit with blue OP17 Rocks D. Xebec. Open that leader page for Rocks Pirates constructed lists.",
        "leaders": [2],
    },
    {
        "slug": "mary-geoise",
        "title": "Mary Geoise One Piece TCG | Imu OPTCG",
        "h2": "Mary Geoise",
        "desc": "Mary Geoise / Empty Throne OPTCG lists live on black OP13 Imu.",
        "copy": "Mary Geoise and the Empty Throne stage belong to black OP13 Imu, not OP17 Elbaph Luffy. Open the Imu page for Five Elders constructed lists.",
        "leaders": [11],
    },
    {
        "slug": "sky-island",
        "title": "Sky Island One Piece TCG | Enel OPTCG",
        "h2": "Sky Island",
        "desc": "Sky Island / Skypeia OPTCG lists live on purple OP15 Enel.",
        "copy": "Sky Island OPTCG on this site is purple OP15 Enel, not yellow OP05 Enel. Ohm, Shura, El Thor, and Mamaragan searches should start on that leader page.",
        "leaders": [12],
    },
    {
        "slug": "skypeia",
        "title": "Skypeia One Piece TCG | Enel OPTCG",
        "h2": "Skypeia",
        "desc": "Skypeia / Sky Island OPTCG lists live on purple OP15 Enel.",
        "copy": "Skypeia is the same search as Sky Island for OPTCG. Purple OP15 Enel is the constructed leader here.",
        "leaders": [12],
    },
    {
        "slug": "egghead",
        "title": "Egghead One Piece TCG | OPTCG",
        "h2": "Egghead",
        "desc": "Egghead-era OPTCG names can start at Luffy, Lucci, and Kizaru-adjacent lists.",
        "copy": "Egghead searches do not have a dedicated leader page yet. Start from Black Luffy, RG Luffy, or the main leader hub, then open a 50-card list that matches your colors.",
        "leaders": [4, 6, 8],
    },
    {
        "slug": "amazon-lily",
        "title": "Amazon Lily One Piece TCG | OPTCG",
        "h2": "Amazon Lily",
        "desc": "Amazon Lily / Hancock OPTCG searches start on this fan hub.",
        "copy": "Boa Hancock does not have a dedicated leader page here yet. Use the leader hub, then yellow or black lists if your Hancock cards match those colors.",
        "leaders": [5, 4],
    },
    {
        "slug": "shichibukai",
        "title": "Warlords One Piece TCG | OPTCG",
        "h2": "Warlords",
        "desc": "Warlord OPTCG pages: Mihawk, Moria, Hancock searches, and related lists.",
        "copy": "Former Warlords on this site with constructed pages are Dracule Mihawk and Gecko Moria. Hancock, Kuma, Crocodile, Doflamingo, and Buggy searches still route through the hub and those two pages.",
        "leaders": [8, 16, 15],
    },
    {
        "slug": "yonko",
        "title": "Yonko One Piece TCG | Four Emperors OPTCG",
        "h2": "Yonko",
        "desc": "Yonko / Four Emperors OPTCG leaders: Shanks, Kaido, Linlin, Luffy, Newgate.",
        "copy": "Yonko is the Japanese search for the Four Emperors. Constructed pages here: green Shanks, purple Kaido, yellow Linlin, black OP17 Luffy, and red Newgate.",
        "leaders": [1, 3, 5, 4, 0],
    },
    {
        "slug": "mugiwara",
        "title": "Mugiwara One Piece TCG | Straw Hat OPTCG",
        "h2": "Mugiwara",
        "desc": "Mugiwara / Straw Hat OPTCG leaders: Luffy, Nami, and Nico Robin.",
        "copy": "Mugiwara is the Straw Hat search. Constructed OPTCG pages: black OP17 Luffy, RG Luffy, Nami, and Nico Robin.",
        "leaders": [4, 6, 7, 17],
    },
    {
        "slug": "optcg-discord",
        "title": "OPTCG Discord | One Piece Deck Base",
        "h2": "OPTCG Discord",
        "desc": "Join the One Piece Deck Base Discord and browse OPTCG decklists.",
        "copy": "The site Discord is linked in the header. Use it to talk lists; use the leader pages to copy 50-card OPTCG decks from Limitless and YouTube.",
        "leaders": [2, 8, 15],
    },
    {
        "slug": "optcg-youtube",
        "title": "OPTCG YouTube decklists | One Piece TCG",
        "h2": "OPTCG YouTube",
        "desc": "YouTube OPTCG deck profiles copied onto leader pages when the 50-card list is public.",
        "copy": "Some leader pages have a Community block for YouTube profiles that posted a real NxSET-NNN list. Those sit above Limitless tournament rows. We do not invent lists from video titles.",
        "leaders": [0, 1, 2, 4],
    },
    {
        "slug": "copy-optcg-decklist",
        "title": "Copy an OPTCG decklist | 50-card",
        "h2": "Copy an OPTCG decklist",
        "desc": "Copy a 50-card OPTCG decklist from a leader page on One Piece Deck Base.",
        "copy": "Open a leader, then a row. The text list is the 50 cards with hover pictures. Consensus lists average the lists already on that page. Card art is from Limitless CDN.",
        "leaders": [2, 8, 15, 6],
    },
]

EXTRA_CHARACTERS = [
    ("Saint Saturn", "saint-saturn", "Five Elders. Black OP13 Imu is the Mary Geoise constructed leader.", [11]),
    ("Saint Warcury", "saint-warcury", "Five Elders. Open the Imu OPTCG page.", [11]),
    ("Saint Nusjuro", "saint-nusjuro", "Five Elders. Open the Imu OPTCG page.", [11]),
    ("Saint Mars", "saint-mars", "Five Elders. Open the Imu OPTCG page.", [11]),
    ("Saint Ju Peter", "saint-ju-peter", "Five Elders. Open the Imu OPTCG page.", [11]),
    ("Five Elders", "five-elders", "Gorosei package. Black OP13 Imu is the constructed OPTCG leader, not OP17 Luffy.", [11]),
    ("Gorosei", "gorosei", "Same search as Five Elders. Open Imu OPTCG lists.", [11]),
    ("Saint Charlos", "saint-charlos", "Celestial Dragon. Imu lists sometimes play Charlos as a flex card.", [11]),
    ("Saint Shalria", "saint-shalria", "Celestial Dragon. See black Imu OPTCG lists.", [11]),
    ("Empty Throne", "empty-throne", "Mary Geoise stage. Starts in play for OP13 Imu.", [11]),
    ("Ohm", "ohm", "Sky Island priest. Purple OP15 Enel lists play Ohm.", [12]),
    ("Shura", "shura", "Sky Island priest. See OP15 Enel OPTCG lists.", [12]),
    ("Gedatsu", "gedatsu", "Sky Island priest. Enel OPTCG is the matching leader.", [12]),
    ("Satori", "satori", "Sky Island priest. Open the Enel leader page.", [12]),
    ("El Thor", "el-thor", "Enel event. Purple OP15 Enel constructed lists are the home.", [12]),
    ("Mamaragan", "mamaragan", "Enel / Katakuri event. See purple Enel and Katakuri lists.", [12, 13]),
    ("Charlotte Pudding", "charlotte-pudding", "Big Mom Pirates. Pudding shows up in Katakuri and Enel purple lists.", [13, 12]),
    ("Charlotte Brulee", "charlotte-brulee", "Big Mom Pirates. Purple OP11 Katakuri lists play Brulee.", [13]),
    ("Bepo", "bepo", "Heart Pirates. Law / Rosinante OPTCG lists are the constructed home.", [14, 6]),
    ("Penguin", "penguin", "Heart Pirates. Open Donquixote Rosinante lists.", [14]),
    ("Shachi", "shachi", "Heart Pirates. Open Donquixote Rosinante lists.", [14]),
    ("Trafalgar D. Water Law", "trafalgar-d-water-law", "Full name search for Trafalgar Law. Rosinante is the Law-engine leader.", [14, 6]),
    ("Sugar", "sugar", "Donquixote Family. Dressrosa searches can start at Sabo and Rosinante.", [15, 14]),
    ("Trebol", "trebol", "Donquixote Family officer. See Sabo / Rosinante Dressrosa pages.", [15, 14]),
    ("Pica", "pica", "Donquixote Family officer. Dressrosa OPTCG starts at Sabo.", [15]),
    ("Diamante", "diamante", "Donquixote Family officer. Open the Sabo leader page.", [15]),
    ("Rebecca", "rebecca", "Dressrosa. Sabo is the constructed Dressrosa leader on this site.", [15]),
    ("Kyros", "kyros", "Dressrosa. Open Sabo OPTCG lists.", [15]),
    ("Koala Revolutionary", "koala-revolutionary", "Same Koala search; Sabo is the Revolutionary Army leader.", [15, 4]),
    ("Hajrudin", "hajrudin", "Giant of Elbaph. Black OP17 Luffy is the Elbaph constructed page.", [4]),
    ("Dorry", "dorry", "Giant. Elbaph Luffy OPTCG lists are related.", [4]),
    ("Brogy", "brogy", "Giant. Elbaph Luffy OPTCG lists are related.", [4]),
    ("Oimo", "oimo", "Giant. Start from Black OP17 Luffy.", [4]),
    ("Kashi", "kashi", "Giant. Start from Black OP17 Luffy.", [4]),
    ("Vegapunk", "vegapunk", "Egghead scientist. No Vegapunk leader page yet; start from Luffy lists.", [4, 6]),
    ("Jewelry Bonney Egghead", "jewelry-bonney-egghead", "Bonney searches can start at RG Luffy until a Bonney leader page exists.", [6]),
    ("Sentomaru Egghead", "sentomaru-egghead", "Egghead marine escort. Use the hub, then a matching color list.", [4, 8]),
    ("Atlas", "atlas", "Vegapunk satellite. Egghead searches start at Luffy pages.", [4]),
    ("Shaka", "shaka", "Vegapunk satellite. Use Black Luffy OPTCG pages.", [4]),
    ("Lilith", "lilith", "Vegapunk satellite. Use the OPTCG hub and Luffy pages.", [4]),
    ("Edison", "edison", "Vegapunk satellite. Start from Luffy OPTCG lists.", [4]),
    ("Pythagoras", "pythagoras", "Vegapunk satellite. Start from Luffy OPTCG lists.", [4]),
    ("York", "york", "Vegapunk satellite. Start from the OPTCG hub.", [4]),
    ("Stussy", "stussy", "CP0. Lucci-adjacent searches can start at Mihawk or the hub.", [8]),
    ("Guernica", "guernica", "CP0. Use the OPTCG hub.", [8, 4]),
    ("Maha", "maha", "CP0. Use the OPTCG hub.", [8]),
    ("Who's-Who", "whos-who", "Tobi Roppo. Purple Kaido OPTCG lists are related.", [3]),
    ("Black Maria", "black-maria", "Tobi Roppo. Open Kaido OPTCG lists.", [3]),
    ("Sasaki", "sasaki", "Tobi Roppo. Open Kaido OPTCG lists.", [3]),
    ("Shinobu", "shinobu", "Wano. Kaido and Luffy OPTCG pages are related.", [3, 4]),
    ("Denjiro", "denjiro", "Wano retainer. Kaido / Luffy OPTCG pages are related.", [3, 4]),
    ("Ashura Doji", "ashura-doji", "Wano retainer. Open Kaido or Luffy lists.", [3, 4]),
    ("Kawamatsu", "kawamatsu", "Wano retainer. Open Kaido or Luffy lists.", [3, 4]),
    ("Raizo", "raizo", "Wano ninja. Open Kaido or Luffy lists.", [3, 4]),
    ("Kiku", "kiku", "Wano. Nami and Wano-adjacent lists are a fair start.", [7, 3]),
    ("Toko", "toko", "Wano. Use the OPTCG hub.", [3, 7]),
    ("Otama", "otama", "Wano. OP13 Ace lists play Otama; Kaido / Luffy pages are related.", [10, 3, 4]),
    ("Izo Wano", "izo-wano", "Izo also shows up in Newgate lists. Red OP17 Newgate is the usual home.", [0, 9]),
    ("Jozu Diamond", "jozu-diamond", "Same Jozu search. Whitebeard OPTCG is Edward Newgate.", [0]),
    ("Namur", "namur", "Whitebeard Pirate. Open Newgate OPTCG lists.", [0]),
    ("Curiel", "curiel", "Whitebeard Pirate. Open Newgate OPTCG lists.", [0]),
    ("Speed Jiru", "speed-jiru", "Whitebeard Pirate. Open Newgate OPTCG lists.", [0]),
    ("Atmos", "atmos", "Whitebeard Pirate. OP13 Ace and Newgate lists may play Atmos.", [10, 0]),
    ("Kingdew", "kingdew", "Whitebeard Pirate. Open Newgate lists.", [0]),
    ("Fossa", "fossa", "Whitebeard Pirate. Open Newgate lists.", [0]),
    ("Blamenco", "blamenco", "Whitebeard Pirate. Open Newgate lists.", [0]),
    ("Rakuyo", "rakuyo", "Whitebeard Pirate. Open Newgate lists.", [0]),
    ("Haruta", "haruta", "Whitebeard Pirate. Open Newgate lists.", [0]),
    ("Benn Beckmann", "benn-beckmann", "Alternate spelling of Benn Beckman. Open OP17 Shanks lists.", [1]),
    ("Limejuice", "limejuice", "Red Hair Pirate. Open Shanks OPTCG lists.", [1]),
    ("Bonk Punch", "bonk-punch", "Red Hair Pirate. Open Shanks OPTCG lists.", [1]),
    ("Building Snake", "building-snake", "Red Hair Pirate. Open Shanks OPTCG lists.", [1]),
    ("Hongo", "hongo", "Red Hair Pirate. Open Shanks OPTCG lists.", [1]),
    ("Howling Gab", "howling-gab", "Red Hair Pirate. Open Shanks OPTCG lists.", [1]),
    ("Monster", "monster", "Red Hair Pirate. Open Shanks OPTCG lists.", [1]),
    ("Gan Fall", "gan-fall", "God of Skypeia. Enel OPTCG is the Sky Island constructed page.", [12]),
    ("Pierre", "pierre", "Gan Fall’s bird. Open Enel lists.", [12]),
    ("Wyper", "wyper", "Shandia warrior. Open Enel OPTCG lists.", [12]),
    ("Aisa", "aisa", "Shandia. Open Enel lists.", [12]),
    ("Calgara", "calgara", "Shandia ancestor. Open Enel or hub pages.", [12]),
    ("Noland", "noland", "Mont Blanc Noland. Sky Island searches start at Enel.", [12]),
    ("Charlestone", "charlestone", "Name that shows up on OPTCG cards. Use the leader hub if you do not see a dedicated page.", [2, 4]),
    ("Crone Oli", "crone-oli", "OPTCG card name. Start from the leader hub, then a color that matches your list.", [4, 3]),
    ("Varie", "varie", "OPTCG card often in purple lists. See Enel and Katakuri pages.", [12, 13]),
    ("Senor Pink", "senor-pink", "Donquixote Family. Dressrosa / Enel flex card in some purple lists.", [12, 15]),
    ("Divine Departure", "divine-departure", "Event card in several purple OPTCG lists. Open Enel, Katakuri, or Kaido.", [12, 13, 3]),
    ("Gamma Knife", "gamma-knife", "Law event. Rosinante and RG Luffy lists are related.", [14, 6]),
    ("Kinemon Wano", "kinemon-wano", "Same Kin'emon search. Kaido and Luffy pages are related.", [3, 4]),
]

SETS = [
    {
        "slug": "op09",
        "code": "OP09",
        "name": "Emperors in the New World",
        "desc": "OP09 OPTCG cards and the Nico Robin leader page.",
        "copy": "OP09 is the set for purple/yellow Nico Robin (OP09-062). Recent Robin 50-card lists on this site include some OP17 cards. Open that leader page for constructed lists.",
        "leaders": [17],
    },
    {
        "slug": "op11",
        "code": "OP11",
        "name": "A Fist of Divine Speed",
        "desc": "OP11 OPTCG: Nami and Charlotte Katakuri leader pages.",
        "copy": "OP11 printed blue/yellow Nami (OP11-041) and purple Charlotte Katakuri (OP11-062). Katakuri is not yellow OP17 Linlin. Open those two leader pages for 50-card lists.",
        "leaders": [7, 13],
    },
    {
        "slug": "op12",
        "code": "OP12",
        "name": "Legacy of the Master",
        "desc": "OP12 OPTCG: Donquixote Rosinante (Corazon) leader page.",
        "copy": "OP12-061 Donquixote Rosinante is the purple/yellow Law engine on this site, not green/blue OP05-022 Rosinante. Open that page for constructed lists.",
        "leaders": [14],
    },
    {
        "slug": "op13",
        "code": "OP13",
        "name": "Carrying on His Will",
        "desc": "OP13 OPTCG: RG Luffy, OP13 Ace, Imu, and Sabo.",
        "copy": "OP13 leaders on this site: red/green OP13-001 RG Luffy, red/blue OP13-002 Ace, black OP13-079 Imu, and red/black OP13-004 Sabo. Do not mix OP13 Ace with OP16 Ace, or Imu with OP17 Luffy, or OP13 Sabo with ST13 Sabo.",
        "leaders": [6, 10, 11, 15],
    },
    {
        "slug": "op14",
        "code": "OP14",
        "name": "The Azure Sea's Compass",
        "desc": "OP14 OPTCG: Mihawk and Gecko Moria leader pages.",
        "copy": "OP14 printed green Mihawk (OP14-020) and black/yellow Gecko Moria (OP14-080). Moria lists on this site include some OP17 cards. Open those leader pages for tournament 50-card lists.",
        "leaders": [8, 16],
    },
    {
        "slug": "op15",
        "code": "OP15",
        "name": "Awakening of the New Era",
        "desc": "OP15 OPTCG: purple Enel leader page.",
        "copy": "OP15-058 Enel is the purple Sky Island leader, not yellow OP05 Enel. Open that page for ramp / rest lists.",
        "leaders": [12],
    },
    {
        "slug": "op16",
        "code": "OP16",
        "name": "Starting Over",
        "desc": "OP16 OPTCG: red Portgas D. Ace leader page.",
        "copy": "OP16-001 Portgas D. Ace is the red rush leader. The red/blue OP13 Ace page is separate. Open OP16 Ace for Whitebeard Pirate rush lists.",
        "leaders": [9, 0],
    },
    {
        "slug": "op17-set",
        "code": "OP17",
        "name": "The World's Strongest Warriors",
        "desc": "OP17 set guide: six color leaders and current-format lists that splash OP17 cards.",
        "copy": "OP17 The World's Strongest Warriors has six leaders on this site, one per color. Sabo, Nico Robin, and Gecko Moria lists have also started packing OP17 cards. Open a leader for 50-card lists sorted by event date.",
        "leaders": [2, 3, 4, 5, 1, 0],
    },
    {
        "slug": "eb04",
        "code": "EB04",
        "name": "Extra Booster",
        "desc": "EB04 cards show up inside constructed OPTCG 50-card lists.",
        "copy": "Extra Booster cards (EB) mix into constructed decks. You will see EB04 lines inside tournament lists on several leader pages. Open a leader, then hover a card ID.",
        "leaders": [3, 2, 8],
    },
    {
        "slug": "prb02",
        "code": "PRB02",
        "name": "Premium Booster",
        "desc": "PRB02 reprints show up in OPTCG constructed lists.",
        "copy": "Premium Booster reprints appear in 50-card lists next to OP and ST cards. Search a leader page for PRB02 in the text list.",
        "leaders": [1, 8, 6],
    },
    {
        "slug": "st13",
        "code": "ST13",
        "name": "Starter Deck",
        "desc": "ST13 is not the OP13 Sabo leader page. Sabo here is OP13-004.",
        "copy": "ST13 is a starter product. The Sabo leader on this site is red/black OP13-004, not ST13 Sabo. Open OP13 Sabo for Dressrosa / Revolutionary Army lists.",
        "leaders": [15],
    },
    {
        "slug": "st32",
        "code": "ST32",
        "name": "Starter Deck",
        "desc": "ST32 cards appear in OP17 Shanks constructed lists.",
        "copy": "ST32 starter cards show up in green Shanks 50-card lists. Open the Shanks leader page and look for ST32 IDs in the text list.",
        "leaders": [1],
    },
]

COMPARES = [
    {
        "slug": "op17-luffy-vs-rg-luffy",
        "title": "OP17 Luffy vs RG Luffy | OPTCG",
        "h2": "OP17 Luffy vs RG Luffy",
        "desc": "Black OP17-079 Monkey D. Luffy is not red/green OP13-001 RG Luffy.",
        "copy": "Black OP17 Luffy is the Elbaph leader. RG Luffy is red/green OP13-001. They do not share a decklist page. Open the one that matches the leader ID on your card.",
        "leaders": [4, 6],
    },
    {
        "slug": "op16-ace-vs-op13-ace",
        "title": "OP16 Ace vs OP13 Ace | OPTCG",
        "h2": "OP16 Ace vs OP13 Ace",
        "desc": "Red OP16-001 Ace is not red/blue OP13-002 Ace.",
        "copy": "OP16 Ace is red, 5 life, Rush support for Whitebeard Pirates. OP13 Ace is red/blue, 3 life, 6000 power. Two pages, two lists. Do not mix them.",
        "leaders": [9, 10],
    },
    {
        "slug": "imu-vs-op17-luffy",
        "title": "Imu vs OP17 Luffy | OPTCG",
        "h2": "Imu vs OP17 Luffy",
        "desc": "Black OP13-079 Imu is not black OP17-079 Monkey D. Luffy.",
        "copy": "Imu is Mary Geoise / Five Elders with a no-2-cost-event rule. OP17 Luffy is Elbaph Straw Hat. Same black color, different IDs (OP13-079 vs OP17-079). Open the matching page.",
        "leaders": [11, 4],
    },
    {
        "slug": "linlin-vs-katakuri",
        "title": "Linlin vs Katakuri | OPTCG",
        "h2": "Linlin vs Katakuri",
        "desc": "Yellow OP17 Charlotte Linlin is not purple OP11 Charlotte Katakuri.",
        "copy": "Linlin is the yellow OP17 Big Mom leader. Katakuri is the purple OP11 leader. Both are Big Mom Pirates. Use the color and set ID on your leader card.",
        "leaders": [5, 13],
    },
    {
        "slug": "op15-enel-not-op05",
        "title": "OP15 Enel vs OP05 Enel | OPTCG",
        "h2": "OP15 Enel vs OP05 Enel",
        "desc": "This site has purple OP15-058 Enel, not yellow OP05 Enel.",
        "copy": "Purple OP15 Enel is the Sky Island ramp leader on this fan site. Yellow OP05 Enel is a different card and is not hosted here. Open OP15 Enel for 50-card lists.",
        "leaders": [12],
    },
    {
        "slug": "op12-rosinante-not-op05",
        "title": "OP12 Rosinante vs OP05 Rosinante | OPTCG",
        "h2": "OP12 vs OP05 Rosinante",
        "desc": "Purple/yellow OP12-061 Corazon is not green/blue OP05-022 Rosinante.",
        "copy": "The Rosinante page on this site is OP12-061 Donquixote Rosinante, the Law engine. Green/blue OP05-022 is a different leader and is not hosted here.",
        "leaders": [14],
    },
    {
        "slug": "op13-sabo-not-st13",
        "title": "OP13 Sabo vs ST13 Sabo | OPTCG",
        "h2": "OP13 Sabo vs ST13 Sabo",
        "desc": "Red/black OP13-004 Sabo is not the ST13 Sabo leader.",
        "copy": "Sabo lists here are OP13-004 Dressrosa / Revolutionary Army. ST13 Sabo is a starter leader and is not on this site. Match the ID on the card.",
        "leaders": [15],
    },
    {
        "slug": "shanks-op17-not-op09",
        "title": "OP17 Shanks vs OP09 Shanks | OPTCG",
        "h2": "OP17 Shanks vs OP09 Shanks",
        "desc": "Green OP17-020 Shanks is not red OP09 Shanks.",
        "copy": "The Shanks page here is green OP17-020 Red Hair. Red OP09 Shanks is a different leader and is not hosted on this site. Open OP17 Shanks for green lists.",
        "leaders": [1],
    },
]

HOWTOS = [
    {
        "slug": "play-one-piece-tcg",
        "title": "How to play One Piece TCG | OPTCG rules basics",
        "h2": "How to play One Piece TCG",
        "desc": "How to play the Bandai One Piece Card Game: leader, 50 cards, DON!!, life.",
        "copy": "Each player has a leader, a 50-card deck, a DON!! deck, and life. You attach DON!! to attack or activate effects. Official rules live on Bandai’s site. This fan site is for copying constructed 50-card lists.",
        "qas": [
            ("How many cards is an OPTCG deck?", "50 cards plus a leader. That is the constructed format used in the lists here."),
            ("Where do I get a list?", "Open a leader page, then a tournament or community row. Hover a name for the English picture."),
            ("Is this official?", "No. Fan site, not affiliated with Bandai or Shueisha. Events stay on Bandai’s site."),
        ],
        "leaders": [2, 8, 6],
    },
    {
        "slug": "optcg-rules",
        "title": "OPTCG rules | One Piece TCG constructed",
        "h2": "OPTCG rules",
        "desc": "OPTCG constructed rules in short: 50 cards, one leader, DON!!, life.",
        "copy": "Constructed OPTCG: one leader, 50 cards, DON!! deck, life equal to the leader’s printed life. Keywords like Rush, Blocker, Banish, and Trigger are on the cards. For the full document, use Bandai. For lists, use a leader page here.",
        "qas": [
            ("What is DON!!?", "The resource you attach each turn. Many leaders spend DON!! −1 or ask for DON!! x1."),
            ("What is a Trigger?", "An effect that can happen when the card is taken as life. Some leaders, like Nico Robin, trash a Trigger from hand."),
        ],
        "leaders": [17, 3, 14],
    },
    {
        "slug": "read-an-optcg-decklist",
        "title": "How to read an OPTCG decklist | NxSET-NNN",
        "h2": "How to read an OPTCG decklist",
        "desc": "OPTCG lists on this site use 4xOP17-039 style lines. Here is how to read them.",
        "copy": "A line like 4xOP17-039 means four copies of set OP17 number 039. Leader IDs look the same (OP17-079, OP13-004). Match the leader ID before you copy the rest of the 50 cards.",
        "qas": [
            ("Why does the leader ID matter?", "Several characters have more than one leader. OP17 Luffy is not RG Luffy. OP16 Ace is not OP13 Ace."),
            ("Why 50 cards?", "Constructed format. Consensus lists on a hub are averaged, then filled back to 50."),
        ],
        "leaders": [4, 6, 9, 10],
    },
    {
        "slug": "optcg-locals-prep",
        "title": "Prep for OPTCG locals | One Piece TCG",
        "h2": "Prep for locals",
        "desc": "How to prep a 50-card OPTCG list for weekly locals.",
        "copy": "Pick a leader you own, open the newest Limitless list on that page, and sleeve the 50 cards. Check Bandai events for a store. We do not list pairings or claim fake finishes.",
        "qas": [
            ("Newest list or consensus?", "Newest date is what people registered this week. Consensus is the average of lists already on the page."),
        ],
        "leaders": [8, 2, 15],
    },
]

SEARCHES = [
    ("luffy decklist", "luffy-decklist", "Monkey D. Luffy OPTCG decklist searches should pick a leader ID: black OP17-079 or red/green OP13-001.", [4, 6]),
    ("zoro decklist", "zoro-decklist", "Zoro is not a leader page here. Zoro cards show up in Mihawk and RG Luffy lists.", [8, 6]),
    ("nami decklist", "nami-decklist", "Nami OPTCG decklists live on blue/yellow OP11-041.", [7]),
    ("shanks decklist", "shanks-decklist", "Shanks OPTCG decklists on this site are green OP17-020, not red OP09 Shanks.", [1]),
    ("kaido decklist", "kaido-decklist", "Kaido OPTCG decklists live on purple OP17-058.", [3]),
    ("whitebeard decklist", "whitebeard-decklist", "Whitebeard OPTCG decklists live on red OP17 Edward Newgate. Ace pages are separate.", [0, 9, 10]),
    ("rocks decklist", "rocks-decklist", "Rocks D. Xebec OPTCG decklists live on blue OP17-039.", [2]),
    ("mihawk decklist", "mihawk-decklist", "Mihawk OPTCG decklists live on green OP14-020.", [8]),
    ("ace decklist", "ace-decklist", "Ace OPTCG: red OP16-001 or red/blue OP13-002. Two pages.", [9, 10]),
    ("enel decklist", "enel-decklist", "Enel OPTCG decklists on this site are purple OP15-058.", [12]),
    ("katakuri decklist", "katakuri-decklist", "Katakuri OPTCG decklists live on purple OP11-062, not yellow Linlin.", [13]),
    ("imu decklist", "imu-decklist", "Imu OPTCG decklists live on black OP13-079, not OP17 Luffy.", [11]),
    ("sabo decklist", "sabo-decklist", "Sabo OPTCG decklists live on red/black OP13-004, not ST13.", [15]),
    ("robin decklist", "robin-decklist", "Nico Robin OPTCG decklists live on purple/yellow OP09-062.", [17]),
    ("moria decklist", "moria-decklist", "Gecko Moria OPTCG decklists live on black/yellow OP14-080.", [16]),
    ("corazon decklist", "corazon-decklist", "Corazon / Rosinante OPTCG decklists live on purple/yellow OP12-061.", [14]),
    ("law decklist", "law-decklist", "Law is the engine on Donquixote Rosinante. Law cards also show up in RG Luffy.", [14, 6]),
    ("big mom decklist", "big-mom-decklist", "Big Mom OPTCG: yellow OP17 Linlin or purple OP11 Katakuri.", [5, 13]),
    ("blackbeard decklist", "blackbeard-decklist", "No Teach leader page yet. Use the hub until one exists.", [3, 4]),
    ("doflamingo decklist", "doflamingo-decklist", "Doflamingo searches should try Sabo and Rosinante Dressrosa pages.", [15, 14]),
    ("one piece tcg deck", "one-piece-tcg-deck", "One Piece TCG deck searches should open a leader, then a 50-card row.", [2, 8, 15]),
    ("op tcg decklist", "op-tcg-decklist", "OP TCG, OPTCG, and One Piece TCG are the same Bandai game on this fan site.", [2, 3, 8]),
    ("bandai optcg", "bandai-optcg", "Bandai publishes the ONE PIECE CARD GAME. Lists here are fan copies of public events.", [2, 8]),
    ("limitless optcg", "limitless-optcg", "Tournament lists on this site are copied from public Limitless Play OPTCG standings.", [2, 8, 3]),
    ("optcg reddit", "optcg-reddit", "Reddit threads often link a leader ID. Match that ID to a page here, then open a real 50-card list.", [2, 8, 6]),
]
